name: Update CSV on Release

on:
  pull_request:
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch CSV file from target repository
        run: |
          # Replace `<target_owner>` with the username or organization name of the target repository owner
          # Replace `<target_repo>` with the name of the target repository
          # Replace `path/to/csv/file.csv` with the actual path to the CSV file in the target repository
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3.raw" \
            -o dcc_config.csv \
            -L "https://raw.githubusercontent.com/adamjtaylor/data_curator_config/main/dcc_config.csv"

      - name: Modify CSV file
        run: |
          # Replace `path/to/csv/file.csv` with the actual path to your CSV file
          # Replace `https://raw.githubusercontent.com/ncihtan/data-models/v23.6.2/HTAN.model.jsonld` with the string containing the version number to be replaced
          # The pattern in the regex assumes the version number has the format `vX.Y.Z`
          # If the format is different, adjust the regex pattern accordingly
          if [[ -n "${{ github.event.ref }}" ]]; then
            sed -i "s|https://raw.githubusercontent.com/ncihtan/data-models/[^/]\+/HTAN.model.jsonld|https://raw.githubusercontent.com/ncihtan/data-models/${{ github.event.ref }}/HTAN.model.jsonld|" dcc_config.csv
          else
            sed -i "s|https://raw.githubusercontent.com/ncihtan/data-models/[^/]\+/HTAN.model.jsonld|https://raw.githubusercontent.com/ncihtan/data-models/${{ github.sha }}/HTAN.model.jsonld|" dcc_config.csv
          fi
      - name: Commit and push changes to target repository
        run: |
          # Set up the GitHub token for authentication
          git config --global credential.helper store
          git config --global user.email "adam.taylor@sagebase.org"
          git config --global user.name "Adam Taylor"
          # Replace `<target_owner>` with the username or organization name of the target repository owner
          # Replace `<target_repo>` with the name of the target repository
          # Replace `update-csv` with the name of the branch you want to push the changes to
          git clone https://github.com/adamjtaylor/data_curator_config.git
          cd data_curator_config
          short_sha=$(echo "${{ github.sha }}" | cut -c 1-7)
          git checkout -b update-csv-${short_sha}
          cp ../dcc_config.csv dcc_config.csv
          git add dcc_config.csv
          git commit -m "Update CSV with release tag"
          git remote set-url origin "https://${{ secrets.DCA_CONFIG_PAT }}@github.com/adamjtaylor/data_curator_config.git"
          git push --set-upstream origin update-csv-${short_sha}
          
      - name: Create pull request
        run: |
          short_sha=$(echo "${{ github.sha }}" | cut -c 1-7)
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.DCA_CONFIG_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/adamjtaylor/data_curator_config/pulls" \
          -d "{
            \"title\": \"Updae CSV with release tag\",
            \"head\": \"update-csv-${short_sha}\",
            \"base\": \"main\",
            \"body\": \"This pull request updates the CSV file with the release tag.\",
            \"draft\": true,
          }"
